import type { ErrorPayload } from '@cardroom/shared';

/** Portuguese copy for error codes; falls back to the server message. */
const MESSAGES: Record<string, string> = {
  UNAUTHORIZED: 'A tua sessão expirou. Entra novamente.',
  PROFILE_REQUIRED: 'Escolhe primeiro um nome de utilizador.',
  VALIDATION: 'Pedido inválido.',
  RATE_LIMITED: 'Calma! Estás a enviar pedidos demasiado depressa.',
  UNKNOWN_GAME: 'Jogo desconhecido.',
  ROOM_NOT_FOUND: 'Não existe nenhuma sala com esse código.',
  ROOM_FULL: 'A sala está cheia.',
  ROOM_IN_PROGRESS: 'Já há uma partida a decorrer nesta sala.',
  NOT_IN_ROOM: 'Não estás nesta sala.',
  NOT_HOST: 'Só o anfitrião pode fazer isso.',
  NOT_READY: 'Ainda há jogadores que não estão prontos (ou estão desligados).',
  ALREADY_IN_ROOM: 'Ainda estás numa partida a decorrer noutra sala.',
  PLAYER_COUNT: 'Número de jogadores inválido para este jogo.',
  CANNOT_KICK: 'Durante a partida só podes remover jogadores desligados.',
  GAME_NOT_RUNNING: 'A partida já terminou.',
  USERNAME_TAKEN: 'Esse nome de utilizador já está a ser usado.',
  NO_SEATING: 'Neste jogo os lugares seguem a ordem de chegada.',
  SEATS_MISSING: 'Todos os lugares da mesa têm de estar ocupados.',
  CHAT_CLOSED: 'O chat abre no fim da mão.',
  NOT_PAUSED: 'A mesa já não está à espera de uma decisão.',
  BUSY: 'O servidor está ocupado, tenta de novo.',
  NETWORK: 'Sem ligação ao servidor.',
  INTERNAL: 'Algo correu mal. Tenta de novo.',
  // Mexicana engine
  NOT_YOUR_TURN: 'Não é a tua vez.',
  ILLEGAL_PLAY: 'Essa carta não pode ser jogada sobre a pilha.',
  MIXED_RANKS: 'Só podes jogar cartas do mesmo valor.',
  PICK_UP_NOT_ALLOWED: 'Tens uma jogada válida — não podes apanhar a pilha.',
  MUST_PLAY_FACE_DOWN: 'Só te restam cartas escondidas.',
  FACE_UP_CARD_REQUIRED: 'Escolhe a carta visível que levas com a pilha.',
  ALREADY_CHOSEN: 'Já escolheste as tuas cartas visíveis.',
  WRONG_PHASE: 'Ação indisponível neste momento.',
  // Fodinha engine
  ALREADY_BID: 'A tua aposta já está fechada.',
  INVALID_BID: 'Essa aposta não é possível nesta ronda.',
  FORBIDDEN_BID: 'O último a apostar não pode fazer a soma das apostas igual ao número de vazas.',
  INVALID_CARD: 'Essa carta não está na tua mão.',
  BLIND_ROUND: 'Na ronda às cegas as cartas são jogadas automaticamente.',
  TOO_MANY_CARDS: 'Não há cartas que cheguem para tantos jogadores com essa mão máxima.',
  // Blackjack engine and session tables
  CANNOT_END: 'A sessão já vai terminar no fim desta ronda.',
  SESSION_ENDING: 'A sessão já vai terminar no fim desta ronda.',
  SESSION_OVER: 'A sessão já terminou.',
  NOT_SEATED: 'Não estás sentado a esta mesa.',
  SITTING_OUT: 'Estás de fora: volta à mesa para apostar.',
  ALREADY_BET: 'Já apostaste nesta ronda.',
  INVALID_BET: 'Aposta fora dos limites da mesa (múltiplos de 10).',
  NOT_ENOUGH_CHIPS: 'Não tens fichas suficientes.',
  NO_BET: 'Não tens aposta para limpar.',
  REBUY_NOT_NEEDED: 'Ainda tens fichas para a aposta mínima.',
  NO_CHANGE: 'Já está assim.',
  NO_OFFER: 'Essa oferta já não está disponível.',
  ILLEGAL_DECISION: 'Essa jogada não é possível com esta mão.',
  SEAT_TAKEN: 'Esse lugar já está ocupado.',
  TABLE_LIMITS: 'Os limites da mesa não batem certo com as fichas iniciais.',
  HINTS_UNSUPPORTED: 'A dica só existe com 4 ou mais baralhos, banca a ficar no 17 mole e carta americana.',
  // Peixinho engine
  MUST_FISH: 'Vai primeiro à pesca: toca numa carta do lago.',
  CANNOT_ASK_SELF: 'Pede a outro jogador.',
  UNKNOWN_TARGET: 'Esse jogador não está à mesa.',
  TARGET_EMPTY: 'Esse jogador já não tem cartas.',
  RANK_NOT_IN_HAND: 'Só podes pedir um valor que tenhas na mão.',
  NOT_FISHING: 'Ninguém te mandou à pesca.',
  INVALID_POND_POSITION: 'Já não há carta nesse sítio do lago.',
  GAME_OVER: 'A partida já terminou.',
  // Desconfia engine
  TOO_SOON: 'Espera um instante: os outros ainda podem desconfiar da jogada anterior.',
  NO_CARDS: 'Escolhe pelo menos uma carta.',
  INVALID_CLAIM: 'Escolhe o valor a anunciar.',
  WRONG_CLAIM: 'A pilha está noutro valor: tens de anunciar esse.',
  LAST_CARD_OPEN: 'Espera: há uma última carta à espera de quem desconfie.',
  DOUBT_CLOSED: 'Tarde demais: essa jogada já não pode ser posta em causa.',
  CANNOT_DOUBT_SELF: 'Não podes desconfiar da tua própria jogada.',
  NOT_PLAYING: 'Já ficaste sem cartas.',
  NEXT_GAME: 'Ainda não estás neste jogo: entras no próximo.',
  // Olho engine
  JOKER_ALONE: 'O joker joga-se sozinho.',
  POWER_FIRST_TRICK: 'Na primeira vaza não se joga 2 nem joker.',
  CANNOT_FINISH_WITH_POWER: 'Nesta mesa não se pode acabar com um 2 ou um joker.',
  NOT_ENOUGH_TWOS: 'Não chegam os 2: para bater uma tripla são precisos pelo menos dois.',
  WRONG_COUNT: 'Joga tantas cartas como a vaza (ou bate com 2s ou com o joker).',
  TOO_LOW: 'Tens de jogar igual ou mais alto.',
  MUST_OPEN: 'Abres tu a vaza: joga alguma coisa.',
  ESCAPE_OR_SKIP: 'Joga a mesma carta para escapar, ou perde a vez.',
  NO_SKIP: 'Ninguém te vai saltar.',
  CANNOT_ESCAPE: 'Não tens com que escapar ao salto.',
  ESCAPE_SAME_CARD: 'Só escapas com a mesma carta, tantas como as jogadas.',
  NO_EXCHANGE: 'Não tens cartas para devolver.',
  RETURN_COUNT: 'Devolve o número certo de cartas.',
  ALREADY_SEATED: 'Já tens lugar nesta mesa.',
  NOT_ENOUGH_PLAYERS: 'À espera de mais jogadores.',
  // Gringo engine
  ALREADY_DONE: 'Já memorizaste as tuas cartas.',
  GRINGO_DISABLED: 'Nesta mesa não se diz Gringo.',
  GRINGO_ALREADY_CALLED: 'Já alguém disse Gringo.',
  GRINGO_TOO_SOON: 'Ainda não: todos têm de jogar mais vezes antes de alguém dizer Gringo.',
  NO_CARDS_LEFT: 'Não tens cartas: só podes dizer Gringo ou passar.',
  DECK_EMPTY: 'O baralho acabou.',
  EMPTY_SLOT: 'Já não há carta nessa posição.',
  NO_POWER: 'Essa carta não tem poder.',
  NO_TARGET: 'Ninguém mais tem cartas para esse poder.',
  WRONG_TARGET: 'Essa carta não serve para este poder.',
  SNAP_CLOSED: 'Tarde demais: já não se pode bater nessa carta.',
  SNAP_TAKEN: 'Alguém bateu primeiro.',
  NO_CARD_TO_GIVE: 'Para bater a carta de outro jogador, precisas de uma carta tua para lhe dar.',
  STALE_WINDOW: 'Essa janela já fechou.',
  // Sueca engine
  NOT_CUTTER: 'Quem corta é outro jogador.',
  MUST_FOLLOW_SUIT: 'Tens de assistir ao naipe.',
  NO_LAST_TRICK: 'Ainda não há nenhuma vaza fechada.',
  LAST_TRICK_USED: 'Já viste a última vaza nesta mão.',
  PAUSED: 'A mesa está à espera de um jogador.',
};

export function describeError(error: ErrorPayload): string {
  return MESSAGES[error.code] ?? error.message;
}
